apiVersion: apps/v1
kind: Deployment
metadata:
 name: database
 labels:
   app: couchdb
spec:
 replicas: 1
 selector:
   matchLabels:
     app: database
 template:
   metadata:
     labels:
       app: database
   spec:
     containers:
     - name: couchdb
       image: couchdb:latest
       ports:
       - containerPort: 5984
       env:
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "root"

---

apiVersion: v1
kind: Service
metadata:
 name: db-service
 labels:
   app: database
spec:
 type: ClusterIP
 ports:
 - port: 5984
 selector:
   app: database